
CREATE TABLE KATEGORIA
  (
    ID    INT NOT NULL ,
    NAZWA VARCHAR (500) NOT NULL
  )

ALTER TABLE KATEGORIA ADD CONSTRAINT KATEGORIA_PK PRIMARY KEY CLUSTERED (ID)

CREATE  TABLE PRODUKTY
  (
    ID           INT NOT NULL ,
    TYTUL           VARCHAR (500) NOT NULL ,
    KATEGORIA_ID    INT NOT NULL ,
    ILOSC_NOMINALNA INT NOT NULL ,
    AUTOR           VARCHAR (500) NOT NULL ,
    UNIKALNY_NUMER  INT NOT NULL
  )
ALTER TABLE PRODUKTY ADD CONSTRAINT PRODUKTY_PK PRIMARY KEY CLUSTERED ("ID ")

CREATE TABLE ROLE
  (
    ID    INT NOT NULL ,
    NAZWA VARCHAR (500) NOT NULL
  )
ALTER TABLE ROLE ADD CONSTRAINT ROLE_PK PRIMARY KEY CLUSTERED (ID)

CREATE  TABLE UZYTKOWNICY
  (
    ID      INT NOT NULL ,
    NAZWA   VARCHAR (500) NOT NULL ,
    HASLO   VARCHAR (500) NOT NULL ,
    EMAIL   VARCHAR (500) NOT NULL ,
    ROLE_ID INT NOT NULL
  )
ALTER TABLE UZYTKOWNICY ADD CONSTRAINT UZYTKOWNICY_PK PRIMARY KEY CLUSTERED (ID


CREATE  TABLE WYPOZYCZENIA
  (
    ID                INT NOT NULL ,
    PRODUKT_ID        INT NOT NULL ,
    UZYTKOWNICY_ID    INT NOT NULL ,
    DATA_WYPOZYCZENIA DATE NOT NULL ,
    DATA_ZWROTU       DATE ,
    ILOSC             INT,
    PRODUKTY_ID    INT NOT NULL
  )

ALTER TABLE WYPOZYCZENIA ADD CONSTRAINT WYPOZYCZENIA_PK PRIMARY KEY CLUSTERED (ID)

ALTER TABLE PRODUKTY ADD CONSTRAINT PRODUKTY_KATEGORIA_FK FOREIGN KEY
(
KATEGORIA_ID
)
REFERENCES KATEGORIA
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION

ALTER TABLE UZYTKOWNICY
ADD CONSTRAINT UZYTKOWNICY_ROLE_FK FOREIGN KEY
(
ROLE_ID
)
REFERENCES ROLE
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION

ALTER TABLE WYPOZYCZENIA
ADD CONSTRAINT WYPOZYCZENIA_PRODUKTY_FK FOREIGN KEY
( PRODUKTY_ID
)
REFERENCES PRODUKTY
( ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE WYPOZYCZENIA ADD CONSTRAINT WYPOZYCZENIA_UZYTKOWNICY_FK FOREIGN KEY
(
UZYTKOWNICY_ID
)
REFERENCES UZYTKOWNICY
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


